package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1

import com.util.SessionUtils;
import java.io.File;
import java.io.Serializable;

/**
 * Directory generated by hbm2java
 */
public class Directory implements java.io.Serializable {

    private int dirId;
    private DirectoryType directoryType;
    private String dirName;
    private String dirAddress;
    private String dirWebsite;
    private String dirDescription;
    private String dirImage;
    private String dirPhone;

    public Directory() {
        directoryType = new DirectoryType();
    }

    public Directory(int dirId) {
        this.dirId = dirId;
    }

    public Directory(int dirId, DirectoryType directoryType, String dirName,
            String dirAddress, String dirWebsite, String dirDescription, String dirImage, String dirPhone) {
        this.dirId = dirId;
        this.directoryType = directoryType;
        this.dirName = dirName;
        this.dirAddress = dirAddress;
        this.dirWebsite = dirWebsite;
        this.dirDescription = dirDescription;
        this.dirImage = dirImage;
        this.dirPhone = dirPhone;
    }

    public int getDirId() {
        return this.dirId;
    }

    public void setDirId(int dirId) {
        this.dirId = dirId;
    }

    public DirectoryType getDirectoryType() {
        return this.directoryType;
    }

    public void setDirectoryType(DirectoryType directoryType) {
        this.directoryType = directoryType;
    }

    public String getDirName() {
        return this.dirName;
    }

    public void setDirName(String dirName) {
        this.dirName = dirName;
    }

    public String getDirAddress() {
        return this.dirAddress;
    }

    public void setDirAddress(String dirAddress) {
        this.dirAddress = dirAddress;
    }

    public String getDirWebsite() {
        return this.dirWebsite;
    }

    public void setDirWebsite(String dirWebsite) {
        this.dirWebsite = dirWebsite;
    }

    public String getDirDescription() {
        return this.dirDescription;
    }

    public void setDirDescription(String dirDescription) {
        this.dirDescription = dirDescription;
    }

    public String getDescriptionSub(int length) {
        if ((dirDescription + "").length() > length) {
            return dirDescription.substring(0, length) + "...";
        } else {
            return dirDescription;
        }
    }

    public String getUrlImage() {
        String location = "resources/upload/";
        if (dirImage != null && !dirImage.equals("")) {
            String location1 = SessionUtils.getRequest().getServletContext().getRealPath("/resources/upload/");
            File f = new File(location1, dirImage);
            if (f.exists()) {
                return location + dirImage;
            } else {
                return "resources/images/" + "company-Icon.png";

            }
        }
        return "resources/images/" + "company-Icon.png";
    }

    public String getUrlImageLarge() {
        String location = "resources/upload/";
        if (dirImage != null && !dirImage.equals("")) {
            String location1 = SessionUtils.getRequest().getServletContext().getRealPath("/resources/upload/");
            File f = new File(location1, dirImage);
            if (f.exists()) {
                return location + dirImage;
            } else {
                return "resources/images/" + "company-Icon.png";

            }
        }
        return "resources/images/" + "company-Icon.png";
    }

    /**
     * @return the dirImage
     */
    public String getDirImage() {
        return dirImage;
    }

    /**
     * @param dirImage the dirImage to set
     */
    public void setDirImage(String dirImage) {
        this.dirImage = dirImage;
    }

    /**
     * @return the dirPhone
     */
    public String getDirPhone() {
        return dirPhone;
    }

    /**
     * @param dirPhone the dirPhone to set
     */
    public void setDirPhone(String dirPhone) {
        this.dirPhone = dirPhone;
    }

}
