package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

    private int distId;
    private Province province;
    private String distName;
    private String distDescription;
    private Set properties = new HashSet(0);

    public District() {
        province=new Province();
    }

    public District(int distId) {
        this.distId = distId;
    }

    public District(int distId, Province province, String distName, String distDescription, Set properties) {
        this.distId = distId;
        this.province = province;
        this.distName = distName;
        this.distDescription = distDescription;
        this.properties = properties;
    }

    public int getDistId() {
        return this.distId;
    }

    public void setDistId(int distId) {
        this.distId = distId;
    }

    public Province getProvince() {
        return this.province;
    }

    public void setProvince(Province province) {
        this.province = province;
    }

    public String getDistName() {
        return this.distName;
    }

    public void setDistName(String distName) {
        this.distName = distName;
    }

    public String getDistDescription() {
        return this.distDescription;
    }

    public void setDistDescription(String distDescription) {
        this.distDescription = distDescription;
    }

    public Set getProperties() {
        return this.properties;
    }

    public void setProperties(Set properties) {
        this.properties = properties;
    }

}
