package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ExchangeType generated by hbm2java
 */
public class ExchangeType  implements java.io.Serializable {


     private int exId;
     private String exName;
     private String exDescription;
     private Set properties = new HashSet(0);

    public ExchangeType() {
    }

	
    public ExchangeType(int exId) {
        this.exId = exId;
    }
    public ExchangeType(int exId, String exName, String exDescription, Set properties) {
       this.exId = exId;
       this.exName = exName;
       this.exDescription = exDescription;
       this.properties = properties;
    }
   
    public int getExId() {
        return this.exId;
    }
    
    public void setExId(int exId) {
        this.exId = exId;
    }
    public String getExName() {
        return this.exName;
    }
    
    public void setExName(String exName) {
        this.exName = exName;
    }
    public String getExDescription() {
        return this.exDescription;
    }
    
    public void setExDescription(String exDescription) {
        this.exDescription = exDescription;
    }
    public Set getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set properties) {
        this.properties = properties;
    }




}


