package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * FavoriteProperty generated by hbm2java
 */
public class FavoriteProperty  implements java.io.Serializable {


     private int favId;
    private Date favCreateDate;
     private Property property;
     private Users users;

    public FavoriteProperty() {
    }

	
    public FavoriteProperty(int favId) {
        this.favId = favId;
    }
    public FavoriteProperty(int favId, Property property, Users users,Date favCreateDate) {
       this.favId = favId;
       this.property = property;
       this.users = users;
       this.favCreateDate = favCreateDate;
    }
   
    public int getFavId() {
        return this.favId;
    }
    
    public void setFavId(int favId) {
        this.favId = favId;
    }
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * @return the favCreateDate
     */
    public Date getFavCreateDate() {
        return favCreateDate;
    }

    /**
     * @param favCreateDate the favCreateDate to set
     */
    public void setFavCreateDate(Date favCreateDate) {
        this.favCreateDate = favCreateDate;
    }




}


