package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * Error generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

    private int feedId;
    private String feedCustomerName;
    private String feedEmail;
    private String feedPhone;
    private String feedMessage;
    private Date feedDate;

    public Feedback() {
    }

    public Feedback(int feedId) {
        this.feedId = feedId;
    }

    public Feedback(int feedId, String feedCustomerName, String feedEmail, String feedPhone, String feedMessage, Date feedDate) {
        this.feedId = feedId;
        this.feedCustomerName = feedCustomerName;
        this.feedEmail = feedEmail;
        this.feedPhone = feedPhone;
        this.feedMessage = feedMessage;
        this.feedDate = feedDate;
    }

    /**
     * @return the feedId
     */
    public int getFeedId() {
        return feedId;
    }

    /**
     * @param feedId the feedId to set
     */
    public void setFeedId(int feedId) {
        this.feedId = feedId;
    }

    /**
     * @return the feedCustomerName
     */
    public String getFeedCustomerName() {
        return feedCustomerName;
    }

    /**
     * @param feedCustomerName the feedCustomerName to set
     */
    public void setFeedCustomerName(String feedCustomerName) {
        this.feedCustomerName = feedCustomerName;
    }

    /**
     * @return the feedEmail
     */
    public String getFeedEmail() {
        return feedEmail;
    }

    /**
     * @param feedEmail the feedEmail to set
     */
    public void setFeedEmail(String feedEmail) {
        this.feedEmail = feedEmail;
    }

    /**
     * @return the feedPhone
     */
    public String getFeedPhone() {
        return feedPhone;
    }

    /**
     * @param feedPhone the feedPhone to set
     */
    public void setFeedPhone(String feedPhone) {
        this.feedPhone = feedPhone;
    }

    /**
     * @return the feedMessage
     */
    public String getFeedMessage() {
        return feedMessage;
    }

    /**
     * @param feedMessage the feedMessage to set
     */
    public void setFeedMessage(String feedMessage) {
        this.feedMessage = feedMessage;
    }

    /**
     * @return the feedDate
     */
    public Date getFeedDate() {
        return feedDate;
    }

    /**
     * @param feedDate the feedDate to set
     */
    public void setFeedDate(Date feedDate) {
        this.feedDate = feedDate;
    }

}
