package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PropertyType generated by hbm2java
 */
public class PropertyType  implements java.io.Serializable {


     private int protId;
     private String protName;
     private String protDescription;
     private Set properties = new HashSet(0);

    public PropertyType() {
    }

	
    public PropertyType(int protId) {
        this.protId = protId;
    }
    public PropertyType(int protId, String protName, String protDescription, Set properties) {
       this.protId = protId;
       this.protName = protName;
       this.protDescription = protDescription;
       this.properties = properties;
    }
   
    public int getProtId() {
        return this.protId;
    }
    
    public void setProtId(int protId) {
        this.protId = protId;
    }

    public String getProtName() {
        return this.protName;
    }
    
    public void setProtName(String protName) {
        this.protName = protName;
    }
    public String getProtDescription() {
        return this.protDescription;
    }
    
    public void setProtDescription(String protDescription) {
        this.protDescription = protDescription;
    }
    public Set getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set properties) {
        this.properties = properties;
    }





}


