package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1

import com.util.SessionUtils;
import java.io.File;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Property generated by hbm2java
 */
public class Property implements java.io.Serializable {

    private long proId;
    private District district;
    private ExchangeType exchangeType;
    private PropertyType propertyType;
    private Users users;
    private Boolean proPublish;
    private String proTitle;
    private String proContent;
    private Long proPrice;
    private Long proDeposit;
    private Long proArea;
    private Boolean proNegotiate;
    private String proAddress;
    private String proContactName;
    private String proContactPhone;
    private String proContactAddress;
    private String proImage;
    private String proImages;
    private String proPosition;
    private String proDirection;
    private Integer proNoOfBathrooms;
    private Integer proNoOfBebrooms;
    private Integer proNoOfFloors;
    private String proFurniture;
    private Date proPublishDate;
    private Date proCreateDate;
    private Integer proStatus;
    private Integer proHit;
    private Set favoriteProperties = new HashSet(0);

    public Property() {
        exchangeType = new ExchangeType();
        propertyType = new PropertyType();
        district = new District();

    }

    public Property(long proId) {
        this.proId = proId;
    }

    public Property(long proId, District district, ExchangeType exchangeType,
            PropertyType propertyType, Users users, Boolean proPublish, String proTitle,
            String proContent, Long proPrice, Long proDeposit, Long proArea, Boolean proNegotiate,
            String proAddress, String proContactName, String proContactPhone, String proContactAddress,
            String proImage, String proImages, String proPosition, String proDirection, Integer proNoOfBathrooms,
            Integer proNoOfBebrooms, Integer proNoOfFloors, String proFurniture, Date proPublishDate,
            Integer proStatus, Integer proHit, Date proCreateDate, Set favoriteProperties) {
        this.proId = proId;
        this.district = district;
        this.exchangeType = exchangeType;
        this.propertyType = propertyType;
        this.users = users;
        this.proPublish = proPublish;
        this.proTitle = proTitle;
        this.proContent = proContent;
        this.proPrice = proPrice;
        this.proDeposit = proDeposit;
        this.proArea = proArea;
        this.proNegotiate = proNegotiate;
        this.proAddress = proAddress;
        this.proContactName = proContactName;
        this.proContactPhone = proContactPhone;
        this.proContactAddress = proContactAddress;
        this.proImage = proImage;
        this.proImages = proImages;
        this.proPosition = proPosition;
        this.proDirection = proDirection;
        this.proNoOfBathrooms = proNoOfBathrooms;
        this.proNoOfBebrooms = proNoOfBebrooms;
        this.proNoOfFloors = proNoOfFloors;
        this.proFurniture = proFurniture;
        this.proPublishDate = proPublishDate;
        this.proCreateDate = proCreateDate;
        this.proStatus = proStatus;
        this.proHit = proHit;
        this.favoriteProperties = favoriteProperties;
    }

    public long getProId() {
        return this.proId;
    }

    public void setProId(long proId) {
        this.proId = proId;
    }

    public District getDistrict() {
        return this.district;
    }

    public void setDistrict(District district) {
        this.district = district;
    }

    public ExchangeType getExchangeType() {
        return this.exchangeType;
    }

    public void setExchangeType(ExchangeType exchangeType) {
        this.exchangeType = exchangeType;
    }

    public PropertyType getPropertyType() {
        return this.propertyType;
    }

    public void setPropertyType(PropertyType propertyType) {
        this.propertyType = propertyType;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Boolean getProPublish() {
        return this.proPublish;
    }

    public void setProPublish(Boolean proPublish) {
        this.proPublish = proPublish;
    }

    public String getProTitle() {
        return this.proTitle;
    }

    public void setProTitle(String proTitle) {
        this.proTitle = proTitle;
    }

    public String getProContent() {
        return this.proContent;
    }

    public void setProContent(String proContent) {
        this.proContent = proContent;
    }

    public Long getProPrice() {
        return this.proPrice;
    }

    public void setProPrice(Long proPrice) {
        this.proPrice = proPrice;
    }

    public Long getProDeposit() {
        return this.proDeposit;
    }

    public void setProDeposit(Long proDeposit) {
        this.proDeposit = proDeposit;
    }

    public Long getProArea() {
        return this.proArea;
    }

    public void setProArea(Long proArea) {
        this.proArea = proArea;
    }

    public Boolean getProNegotiate() {
        return this.proNegotiate;
    }

    public void setProNegotiate(Boolean proNegotiate) {
        this.proNegotiate = proNegotiate;
    }

    public String getProAddress() {
        return this.proAddress;
    }

    public void setProAddress(String proAddress) {
        this.proAddress = proAddress;
    }

    public String getProContactName() {
        return this.proContactName;
    }

    public void setProContactName(String proContactName) {
        this.proContactName = proContactName;
    }

    public String getProContactPhone() {
        return this.proContactPhone;
    }

    public void setProContactPhone(String proContactPhone) {
        this.proContactPhone = proContactPhone;
    }

    public String getProContactAddress() {
        return this.proContactAddress;
    }

    public void setProContactAddress(String proContactAddress) {
        this.proContactAddress = proContactAddress;
    }

    public String getProImage() {
        return this.proImage;
    }

    public void setProImage(String proImage) {
        this.proImage = proImage;
    }

    public String getProPosition() {
        return this.proPosition;
    }

    public void setProPosition(String proPosition) {
        this.proPosition = proPosition;
    }

    public String getProDirection() {
        return this.proDirection;
    }

    public void setProDirection(String proDirection) {
        this.proDirection = proDirection;
    }

    public Integer getProNoOfBathrooms() {
        return this.proNoOfBathrooms;
    }

    public void setProNoOfBathrooms(Integer proNoOfBathrooms) {
        this.proNoOfBathrooms = proNoOfBathrooms;
    }

    public Integer getProNoOfBebrooms() {
        return this.proNoOfBebrooms;
    }

    public void setProNoOfBebrooms(Integer proNoOfBebrooms) {
        this.proNoOfBebrooms = proNoOfBebrooms;
    }

    public Integer getProNoOfFloors() {
        return this.proNoOfFloors;
    }

    public void setProNoOfFloors(Integer proNoOfFloors) {
        this.proNoOfFloors = proNoOfFloors;
    }

    public String getProFurniture() {
        return this.proFurniture;
    }

    public void setProFurniture(String proFurniture) {
        this.proFurniture = proFurniture;
    }

    public Date getProPublishDate() {
        return this.proPublishDate;
    }

    public void setProPublishDate(Date proPublishDate) {
        this.proPublishDate = proPublishDate;
    }

    public Integer getProStatus() {
        return this.proStatus;
    }

    public void setProStatus(Integer proStatus) {
        this.proStatus = proStatus;
    }

    public Integer getProHit() {
        return this.proHit;
    }

    public void setProHit(Integer proHit) {
        this.proHit = proHit;
    }

    public Set getFavoriteProperties() {
        return this.favoriteProperties;
    }

    public void setFavoriteProperties(Set favoriteProperties) {
        this.favoriteProperties = favoriteProperties;
    }

    /**
     * @return the proImages
     */
    public String getProImages() {
        return proImages;
    }

    /**
     * @param proImages the proImages to set
     */
    public void setProImages(String proImages) {
        this.proImages = proImages;
    }

    /**
     * @return the proCreateDate
     */
    public Date getProCreateDate() {
        return proCreateDate;
    }

    /**
     * @param proCreateDate the proCreateDate to set
     */
    public void setProCreateDate(Date proCreateDate) {
        this.proCreateDate = proCreateDate;
    }

    public String getUrlImage() {
        String location = "./resources/upload/";
        if (proImage != null && !proImage.equals("")) {
            String location1 = SessionUtils.getRequest().getServletContext().getRealPath("/resources/upload/");
            File f = new File(location1, proImage);
            if (f.exists()) {
                return location + proImage;
            } else {
                return "./resources/images/" + "thumb.jpg";

            }
        }
        return "./resources/images/" + "thumb.jpg";
    }

    public String getUrlImageLarge() {
        String location = "./resources/upload/";
        if (proImage != null && !proImage.equals("")) {
            String location1 = SessionUtils.getRequest().getServletContext().getRealPath("/resources/upload/");
            File f = new File(location1, proImage);
            if (f.exists()) {
                return location + proImage;
            } else {
                return "./resources/images/" + "big_pic.jpg";

            }
        }
        return "./resources/images/" + "big_pic.jpg";
    }

    public String getContentSub(int length) {
        if (proContent.length() > length) {
            return proContent.substring(0, length) + "...";
        } else {
            return proContent;
        }
    }

    public String getTitleSub(int length) {
        if (proTitle.length() > length) {
            return proTitle.substring(0, length) + "...";
        } else {
            return proTitle;
        }
    }

    public String getLat() {
        if (proPosition != null && !proPosition.equals("")) {
            String[] pos = proPosition.split(",");
            return pos[0];
        } else {
            return "";
        }
    }

    public String getLng() {
        if (proPosition != null && !proPosition.equals("")) {
            String[] pos = proPosition.split(",");
            return pos[1];
        } else {
            return "";
        }
    }

}
