package com.entity;
// Generated Jan 4, 2015 2:41:11 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String UUsername;
     private String UPassword;
     private String UFullname;
     private String UPhone;
     private String UTelephone;
     private String UEmail;
     private String UDescription;
     private Boolean UActived;
     private Boolean UIsAdmin;
     private Set favoriteProperties = new HashSet(0);
     private Set properties = new HashSet(0);

    public Users() {
    }

	
    public Users(String UUsername) {
        this.UUsername = UUsername;
    }
    public Users(String UUsername, String UPassword, String UFullname, String UPhone, String UTelephone, String UEmail, String UDescription, Boolean UActived, Boolean UIsAdmin, Set favoriteProperties, Set properties) {
       this.UUsername = UUsername;
       this.UPassword = UPassword;
       this.UFullname = UFullname;
       this.UPhone = UPhone;
       this.UTelephone = UTelephone;
       this.UEmail = UEmail;
       this.UDescription = UDescription;
       this.UActived = UActived;
       this.UIsAdmin = UIsAdmin;
       this.favoriteProperties = favoriteProperties;
       this.properties = properties;
    }
   
    public String getUUsername() {
        return this.UUsername;
    }
    
    public void setUUsername(String UUsername) {
        this.UUsername = UUsername;
    }
    public String getUPassword() {
        return this.UPassword;
    }
    
    public void setUPassword(String UPassword) {
        this.UPassword = UPassword;
    }
    public String getUFullname() {
        return this.UFullname;
    }
    
    public void setUFullname(String UFullname) {
        this.UFullname = UFullname;
    }
    public String getUPhone() {
        return this.UPhone;
    }
    
    public void setUPhone(String UPhone) {
        this.UPhone = UPhone;
    }
    public String getUTelephone() {
        return this.UTelephone;
    }
    
    public void setUTelephone(String UTelephone) {
        this.UTelephone = UTelephone;
    }
    public String getUEmail() {
        return this.UEmail;
    }
    
    public void setUEmail(String UEmail) {
        this.UEmail = UEmail;
    }
    public String getUDescription() {
        return this.UDescription;
    }
    
    public void setUDescription(String UDescription) {
        this.UDescription = UDescription;
    }
    public Boolean getUActived() {
        return this.UActived;
    }
    
    public void setUActived(Boolean UActived) {
        this.UActived = UActived;
    }
    public Boolean getUIsAdmin() {
        return this.UIsAdmin;
    }
    
    public void setUIsAdmin(Boolean UIsAdmin) {
        this.UIsAdmin = UIsAdmin;
    }
    public Set getFavoriteProperties() {
        return this.favoriteProperties;
    }
    
    public void setFavoriteProperties(Set favoriteProperties) {
        this.favoriteProperties = favoriteProperties;
    }
    public Set getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set properties) {
        this.properties = properties;
    }

    public int getSizeOfProperty(){
        return this.properties.size();
    }



}


